### ISSUE TITLE
Add support for limit parameter in paginator

### ISSUE THREAD

**Issue by DavidHuie** [nationbuilder/nationbuilder-rb#11]
We currently limit users of the client to pages of size 10.

**Comment by codealchemy** [comment]
@DavidHuie the limit set in the initial request when starting pagination is retained when results are paginated, how would you like to see this implemented?

Currently:
```
response = client.call(:people, :index, limit: 100)
page1 = NationBuilder::Paginator.new(client, response)
page1.body['results'].count
=> 100
page2 = page1.next
page2.body['results'].count
=> 100
```

**Comment by DavidHuie** [comment]
I don't think this is necessary, actually. Once you've set the limit in the original call, I don't think you can change the page size anymore (@aq1018 can correct me).

**Comment by aq1018** [comment]
I think @codealchemy wants to retain pagination data when calling pages repeatedly.

**Comment by codealchemy** [comment]
@aq1018 @DavidHuie is this good to close?

**Comment by DavidHuie** [comment]
@codealchemy I think that's up to you.

**Comment by DavidHuie** [comment]
I stand corrected: the limit can be changed in subsequent pagination calls. I think a nice API for this looks like this:

```ruby
page2 = page1.next(limit: 100)
```

**Comment by DavidHuie** [comment]
The built-in CGI library can parse the query string. For converting back to a query string, you can follow these steps: http://stackoverflow.com/a/11251654
