### ISSUE TITLE
Raise error if rate limit retries exhausted

### ISSUE THREAD

**Issue by bxjx** [nationbuilder/nationbuilder-rb#12]
Currently, if all retries are exhausted, the code will not raise an error. It will instead return a nil parsed response. It would be great if it raised an error on the final attempt. It would also be great if it was possible to access the rate limit headers through this exception (rather than just the response body which is a string).

Happy to code something and submit :)

**Comment by bxjx** [comment]
@DavidHuie any thoughts on this? :)

**Comment by DavidHuie** [comment]
This is implemented on 1.3.2. Thanks for the suggestion, @bxjx.

**Comment by bxjx** [comment]
Excellent. Thanks @DavidHuie !
