### ISSUE TITLE
Found this bug on nation builder, don't know where to put it, really like the site and wanted to share the company!

### ISSUE THREAD

**Issue by slotaj** [nationbuilder/nationbuilder-rb#26]
![nation builder error](https://cloud.githubusercontent.com/assets/12905774/13561113/2b9679c2-e3e6-11e5-9b51-8e51a5880793.png)

**Comment by codealchemy** [comment]
Hey @slotaj, thanks for reaching out! That looks to be a website issue - if you could please connect with someone on our support team at help@nationbuilder.com or 1-213-394-4623 with the slug of the nation (or website you found that on) we can work towards resolving it. Hope this helps!
